name: abcdef
on:
  pull_request:
  
  
jobs:
  first:
    runs-on: ubuntu-latest
    
    steps:
      - name: testing
        run: |
          echo Hellow okowkrks
          echo ${{ toJson(github.event.pull_request.commits[0]) }}
          echo ${{ github.event.pull_request.commits[0].sha }}
          echo ${{ github.event.pull_request._links.commits }}
          echo ${{ github.event.pull_request.commits[0].author.name }}
          echo ${{ github.event.pull_request.commits[0].committer.name }}
          echo ${{ github.event.commits[0].author.name }}
          echo ${{ github.event.commits[0].committer.name }}
          echo ${{ github.event.pull_request.user.login }}
          echo ${{ github.event.pull_request.user.email }}
          echo ${{ secrets.GITHUB_TOKEN }} | cut -c1-5
