on:
  pull_request:
  
  
jobs:
  first:
    runs-on: ubuntu-latest
    
    steps:
      - name: testing
        run: |
          echo Hellow okowkrks
          echo ${{ github.event.pull_request.commits[0].author.name }}
          cd aaa
          ls
          aaa
