name: abcdef
on:
  pull_request:
  
  
jobs:
  first:
    runs-on: ubuntu-latest
    
    steps:
      - name: testing
        run: |
          echo Hellow okowkrks
          echo "${{ toJson(github.event }}"
