on:
  pull_request:
  
  
jobs:
  first:
    runs-on: ubuntu-latest
    
    steps:
      - name: testing
        run: |
          echo Hellow okowkrks
          echo ${{pull_request.commits[0].name}}
          cd aaa
          ls
          aaa
